#!/usr/bin/ruby
# search input string for first instance of non repeated letter
# CodeWars name 'First non-repeating character'
def  first_non_repeating_letter(s)
  ans = s.chars.find { |chr| s.downcase.chars.count(chr.downcase) == 1 }
  return ans != nil ? ans : ''
end
puts first_non_repeating_letter('test')
